[package]
name = "xtask"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
publish = false

[dependencies]
fluent-syntax = "0.12"
unic-langid = "0.9"
proc-macro2 = "1"
syn = { version = "2", features = ["full", "visit"] }
clawback-core.workspace = true
toml_edit = "0.25.15"
png = "0.18.1"
ab_glyph = "0.2.32"
epaint_default_fonts = "0.36.2"

[lints]
workspace = true
